services:
  mongo:
    image: mongo:7
    container_name: gamex-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build: ./server
    container_name: user-service
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/gamex-users
  next-app:
    build:
      context: ./client
      target: runner
      args:
        NEXT_PUBLIC_BASE_URL: "http://localhost:4000"
        NEXT_PUBLIC_CLIENT_SUCCESS_REDIRECT: "http://localhost:3000/homepage"
    container_name: next-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - user-service
    environment:
      NODE_ENV: production
      PORT: 3000

volumes:
  mongo-data: