name: Build & Push Docker Images

on:
  push:
    branches: ["main"]
    tags: ["v*"]          
  pull_request:
    branches: ["main"]    

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_NAMESPACE: ${{ secrets.DOCKERHUB_USERNAME }}
      NEXT_PUBLIC_BASE_URL: http://localhost:4000
      NEXT_PUBLIC_CLIENT_SUCCESS_REDIRECT: http://localhost:3000/homepage

    strategy:
      matrix:
        include:
          - name: user-service
            context: server
            dockerfile: server/Dockerfile
            image_name: gamex-user-service
            build_args: |
              NODE_ENV=production
          - name: frontend
            context: client
            dockerfile: client/Dockerfile
            image_name: gamex-frontend
            build_args: |
              NEXT_PUBLIC_BASE_URL=http://localhost:4000
              NEXT_PUBLIC_CLIENT_SUCCESS_REDIRECT=http://localhost:3000/homepage

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_NAMESPACE }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tags/labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_NAMESPACE }}/${{ matrix.image_name }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=sha

      - name: Build (and push on main/tags)
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ matrix.build_args }}
          platforms: linux/amd64
